#define _CRT_SEURE_NO_WARNINGS
#include <stdio.h>

void merge(int* A, int p, int q, int r, int* temp) {
	int i, j, t;

	i = p;
	j = q + 1;
	t = p;
	
	while (i <= q && j <= r) {
		if (A[i] < A[j]) {
			temp[t] = A[i];
			t++; i++;
		}
		else {
			temp[t] = A[j];
			t++; j++;
		}
	}

	if (j > r) // 이 부분이 j < r 일 경우가 먼저 배치 되면 오버플로우 발생함. 왜지?
		// gpt는 
		for (; i <= q; i++, t++)
			temp[t] = A[i];
	else
		for (; j <= r; j++, t++)
			temp[t] = A[j];

	for (i = p; i <= r; i++)
		A[i] = temp[i];
}
void mergeSort(int* A, int p, int r, int* temp) {
	int q;

	if (p < r) {
		q = (p + r) / 2;
		mergeSort(A, p, q, temp);
		mergeSort(A, q + 1, r, temp);
		merge(A, p, q, r, temp);
	}
}
